import os
import importlib.util
import inspect

def generate_directory_inits(dirs=["Entities", 
                            "Components", 
                            "Enums",]):

    for dir in dirs:
        init_path = os.path.join(dir, "__init__.py")
        imports = []

        for filename in os.listdir(dir):
            if filename.endswith(".py") and filename != "__init__.py":
                module_name = filename[:-3]
                filepath = os.path.join(dir, filename)

                spec = importlib.util.spec_from_file_location(f"{dir}.{module_name}", filepath)
                mod = importlib.util.module_from_spec(spec)
                spec.loader.exec_module(mod)

                for name, obj in inspect.getmembers(mod, inspect.isclass):
                    if obj.__module__ == mod.__name__:
                        imports.append(f"from .{module_name} import {name}")

        with open(init_path, "w") as f:
            f.write("# Auto-generated by generate_ECS_inits.py\n")
            f.write("\n".join(imports) + "\n")

        print(f"[✓] Generated {init_path} with {len(imports)} {dir} imports.")
